name: Test C3 package

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  test:
    name: Run C3 tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup C3
        uses: jotrorox/setup-c3@v1

      - name: Run tests
        run: c3c compile-test .
